<?php
return [
    ['city_name' => 'Mumbai', 'city_state' => 'Maharashtra'],
    ['city_name' => 'Delhi', 'city_state' => 'Delhi'],
    ['city_name' => 'Bengaluru', 'city_state' => 'Karnataka'],
    ['city_name' => 'Hyderabad', 'city_state' => 'Telangana'],
    ['city_name' => 'Ahmedabad', 'city_state' => 'Gujarat'],
    ['city_name' => 'Chennai', 'city_state' => 'Tamil Nadu'],
    ['city_name' => 'Kolkata', 'city_state' => 'West Bengal'],
    ['city_name' => 'Pune', 'city_state' => 'Maharashtra'],
    ['city_name' => 'Jaipur', 'city_state' => 'Rajasthan'],
    ['city_name' => 'Lucknow', 'city_state' => 'Uttar Pradesh'],
    ['city_name' => 'Kanpur', 'city_state' => 'Uttar Pradesh'],
    ['city_name' => 'Nagpur', 'city_state' => 'Maharashtra'],
    ['city_name' => 'Indore', 'city_state' => 'Madhya Pradesh'],
    ['city_name' => 'Thane', 'city_state' => 'Maharashtra'],
    ['city_name' => 'Bhopal', 'city_state' => 'Madhya Pradesh'],
    ['city_name' => 'Visakhapatnam', 'city_state' => 'Andhra Pradesh'],
    ['city_name' => 'Pimpri-Chinchwad', 'city_state' => 'Maharashtra'],
    ['city_name' => 'Patna', 'city_state' => 'Bihar'],
    ['city_name' => 'Vadodara', 'city_state' => 'Gujarat'],
    ['city_name' => 'Ghaziabad', 'city_state' => 'Uttar Pradesh'],
    ['city_name' => 'Ludhiana', 'city_state' => 'Punjab'],
    ['city_name' => 'Agra', 'city_state' => 'Uttar Pradesh'],
    ['city_name' => 'Nashik', 'city_state' => 'Maharashtra'],
    ['city_name' => 'Faridabad', 'city_state' => 'Haryana'],
    ['city_name' => 'Meerut', 'city_state' => 'Uttar Pradesh'],
    ['city_name' => 'Rajkot', 'city_state' => 'Gujarat'],
    ['city_name' => 'Kalyan-Dombivli', 'city_state' => 'Maharashtra'],
    ['city_name' => 'Vasai-Virar', 'city_state' => 'Maharashtra'],
    ['city_name' => 'Varanasi', 'city_state' => 'Uttar Pradesh'],
    ['city_name' => 'Srinagar', 'city_state' => 'Jammu and Kashmir'],
    ['city_name' => 'Aurangabad', 'city_state' => 'Maharashtra'],
    ['city_name' => 'Dhanbad', 'city_state' => 'Jharkhand'],
    ['city_name' => 'Amritsar', 'city_state' => 'Punjab'],
    ['city_name' => 'Navi Mumbai', 'city_state' => 'Maharashtra'],
    ['city_name' => 'Allahabad', 'city_state' => 'Uttar Pradesh'],
    ['city_name' => 'Ranchi', 'city_state' => 'Jharkhand'],
    ['city_name' => 'Howrah', 'city_state' => 'West Bengal'],
    ['city_name' => 'Coimbatore', 'city_state' => 'Tamil Nadu'],
    ['city_name' => 'Jabalpur', 'city_state' => 'Madhya Pradesh'],
    ['city_name' => 'Gwalior', 'city_state' => 'Madhya Pradesh'],
    ['city_name' => 'Vijayawada', 'city_state' => 'Andhra Pradesh'],
    ['city_name' => 'Jodhpur', 'city_state' => 'Rajasthan'],
    ['city_name' => 'Madurai', 'city_state' => 'Tamil Nadu'],
    ['city_name' => 'Raipur', 'city_state' => 'Chhattisgarh'],
    ['city_name' => 'Kota', 'city_state' => 'Rajasthan'],
    ['city_name' => 'Guwahati', 'city_state' => 'Assam'],
];