<?php

if (! function_exists('getConstants')) {
    function getConstants()
    {
        return [
            'employment_types' => [
                'salaried' => 'Salaried',
                'self_employed' => 'Self Employed',
                'business' => 'Business',
                'government' => 'Government Employee',
                'private' => 'Private Employee',
                'student' => 'Student',
                'unemployed' => 'Unemployed',
                'retired' => 'Retired',
                'freelancer' => 'Freelancer',
                'contract' => 'Contract Employee',
                'part_time' => 'Part Time',
                'full_time' => 'Full Time',
                'intern' => 'Intern',
                'volunteer' => 'Volunteer',
                'homemaker' => 'Homemaker',
                'other' => 'Other',
            ],

            'platform_types' => [
                'instagram' => 'Instagram',
                'facebook' => 'Facebook',
                'twitter' => 'Twitter',
                'youtube' => 'YouTube',
                'linkedin' => 'LinkedIn',
                'whatsapp' => 'WhatsApp',
                'telegram' => 'Telegram',
                'snapchat' => 'SnapChat',
                'pinterest' => 'Pinterest',
                'tiktok' => 'TikTok',
                'reddit' => 'Reddit',
                'discord' => 'Discord',
                'twitch' => 'Twitch',
                'wechat' => 'WeChat',
                'signal' => 'Signal',
                'threads' => 'Threads',
                'others' => 'Others',
            ],

            'father_occupations' => [
                'farmer' => 'Farmer',
                'business' => 'Business',
                'government_employee' => 'Government Employee',
                'private_employee' => 'Private Employee',
                'teacher' => 'Teacher',
                'doctor' => 'Doctor',
                'engineer' => 'Engineer',
                'retired' => 'Retired',
                'deceased' => 'Deceased',
                'driver' => 'Driver',
                'shopkeeper' => 'Shopkeeper',
                'labour' => 'Labour',
                'police' => 'Police Officer',
                'military' => 'Military Service',
                'advocate' => 'Advocate/Lawyer',
                'accountant' => 'Accountant',
                'architect' => 'Architect',
                'artist' => 'Artist',
                'banker' => 'Banker',
                'chef' => 'Chef',
                'consultant' => 'Consultant',
                'contractor' => 'Contractor',
                'dancer' => 'Dancer',
                'designer' => 'Designer',
                'editor' => 'Editor',
                'electrician' => 'Electrician',
                'fisherman' => 'Fisherman',
                'florist' => 'Florist',
                'gardener' => 'Gardener',
                'hairdresser' => 'Hairdresser',
                'journalist' => 'Journalist',
                'judge' => 'Judge',
                'manager' => 'Manager',
                'mechanic' => 'Mechanic',
                'musician' => 'Musician',
                'nurse' => 'Nurse',
                'painter' => 'Painter',
                'pharmacist' => 'Pharmacist',
                'photographer' => 'Photographer',
                'pilot' => 'Pilot',
                'plumber' => 'Plumber',
                'writer' => 'Writer',
                'other' => 'Other',
            ],

            'mother_occupations' => [
                'homemaker' => 'Homemaker',
                'business' => 'Business',
                'government_employee' => 'Government Employee',
                'private_employee' => 'Private Employee',
                'teacher' => 'Teacher',
                'doctor' => 'Doctor',
                'nurse' => 'Nurse',
                'retired' => 'Retired',
                'deceased' => 'Deceased',
                'farmer' => 'Farmer',
                'tailor' => 'Tailor',
                'beautician' => 'Beautician',
                'labour' => 'Labour',
                'accountant' => 'Accountant',
                'artist' => 'Artist',
                'banker' => 'Banker',
                'consultant' => 'Consultant',
                'designer' => 'Designer',
                'editor' => 'Editor',
                'florist' => 'Florist',
                'gardener' => 'Gardener',
                'hairdresser' => 'Hairdresser',
                'journalist' => 'Journalist',
                'manager' => 'Manager',
                'musician' => 'Musician',
                'painter' => 'Painter',
                'pharmacist' => 'Pharmacist',
                'photographer' => 'Photographer',
                'writer' => 'Writer',
                'other' => 'Other',
            ],

            'relation_types' => [
                'wife' => 'Wife',
                'husband' => 'Husband',
                'father' => 'Father',
                'mother' => 'Mother',
                'brother' => 'Brother',
                'sister' => 'Sister',
                'son' => 'Son',
                'daughter' => 'Daughter',
                'grandfather' => 'Grandfather',
                'grandmother' => 'Grandmother',
                'uncle' => 'Uncle',
                'aunt' => 'Aunt',
                'nephew' => 'Nephew',
                'niece' => 'Niece',
                'cousin' => 'Cousin',
                'friend' => 'Friend',
                'colleague' => 'Colleague',
                'partner' => 'Partner',
                'fiance' => 'Fiance',
                'fiancee' => 'Fiancee',
                'guardian' => 'Guardian',
                'other' => 'Other',
            ],

            'religions' => [
                'hinduism' => 'Hinduism',
                'islam' => 'Islam',
                'christianity' => 'Christianity',
                'sikhism' => 'Sikhism',
                'buddhism' => 'Buddhism',
                'jainism' => 'Jainism',
                'judaism' => 'Judaism',
                'bahai' => 'Bahai',
                'shinto' => 'Shinto',
                'taoism' => 'Taoism',
                'confucianism' => 'Confucianism',
                'zoroastrianism' => 'Zoroastrianism',
                'agnostic' => 'Agnostic',
                'atheist' => 'Atheist',
                'spiritual' => 'Spiritual',
                'other' => 'Other',
                'none' => 'None',
            ],

            'castes' => [
                'general' => 'General',
                'obc' => 'OBC (Other Backward Class)',
                'sc' => 'SC (Scheduled Caste)',
                'st' => 'ST (Scheduled Tribe)',
                'ews' => 'EWS (Economically Weaker Section)',
                'brahmin' => 'Brahmin',
                'kshatriya' => 'Kshatriya',
                'vaishya' => 'Vaishya',
                'shudra' => 'Shudra',
                'jain' => 'Jain',
                'muslim' => 'Muslim',
                'christian' => 'Christian',
                'sikh' => 'Sikh',
                'buddhist' => 'Buddhist',
                'other' => 'Other',
                'not_applicable' => 'Not Applicable',
            ],
            'person' => [
                'public' => 'Public',
                'private' => 'Private',
                'onlyme' => 'Only Me',
            ],
            'grade' => [
                'a' => 'a',
                'a+' => 'a+',
                'b' => 'b',
                'b+' => 'b+',
                'c' => 'c',
                'c+' => 'c+',
                'd' => 'd',
                'd+' => 'd+',
            ],
        ];
    }
}
